apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: hoa-pipeline
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: consumer:latest
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_HOST
          value: "hoa-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: hoa-rabbitmq-default-user
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hoa-rabbitmq-default-user
              key: password
        - name: RABBITMQ_QUEUE
          value: "test_queue"
        volumeMounts:
        - name: shared-storage
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        restartPolicy: Always
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: producer-consumer-pvc
      restartPolicy: Always
