apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: hoa-pipeline
  labels:
    app: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui
        image: web-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: RABBITMQ_HOST
          value: "hoa-rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: hoa-rabbitmq-default-user
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hoa-rabbitmq-default-user
              key: password
        - name: RABBITMQ_QUEUE
          value: "test_queue"
        volumeMounts:
        - name: shared-storage
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: producer-consumer-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  namespace: hoa-pipeline
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: web-ui
